
name: flake8 Lint
on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8-Lint
        id: result
        run: | 
              pip install flake8
              pip install flake8-dashboard
              flake8 . --exit-zero --format=dashboard